siteTitle: "SimpleIPAM"

replicaCount: 1

image:
  repository: ghcr.io/teamzuzu/simpleipam
  tag: master
  pullPolicy: Always

service:
  type: ClusterIP
  port: 888

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClassName: ""
  dbPath: /simpleipam/sqlite/ipam.db
  localPath: /simpleipam/local/

ingress:
  enabled: false
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: simpleipam.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
