apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simpleipam.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "simpleipam.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "simpleipam.name" . }}
    spec:
      initContainers:
        - name: setup-simpleipam
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          image: ghcr.io/teamzuzu/zuzu-devops:main
          command: ["bash", "-xc"]
          args:
            - |
              if [[ ! -s /local/ipam.db ]] ; then touch /local/ipam.db ; fi
              if [[ ! -s /local/index.html ]] ; then touch /local/index.html ; fi
          volumeMounts:
            - name: local-data
              mountPath: '/local'
      containers:
        - name: simpleipam
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            - name: local-data
              mountPath: {{ .Values.persistence.dbPath }}
              subPath: ipam.db
            - name: local-data
              mountPath: {{ .Values.persistence.localPath }}
      volumes:
        - name: local-data
          persistentVolumeClaim:
            claimName: local-data-pvc
